apiVersion: apps/v1
kind: Deployment
metadata:  
  labels:
    app: nginx-demo    
  name: nginx-demo  
spec:  
  replicas: 5  
  selector:
    matchLabels:
      app: nginx-demo  
  template:
    metadata:      
      labels:
        app: nginx-demo
    spec:
      containers:
      - image: nginx        
        name: nginx        
        ports:
        - containerPort: 80
